encryptionsalt: v1:oDcxDsfN9Eo=:v1:USbSUOOQGHNP8pqY:j3a8qL5jMQEaqDaktHAndt2oI6Gj6g==
name: metaflow
runtime: python
config:
    metaflow-aws:security:
        alb: true
        allowed_cidrs: [103.7.207.238/32] # 0.0.0.0/0 for "everyone"
    metaflow-aws:metadata-service:
        image: docker.io/netflixoss/metaflow_metadata_service:v2.5.1
        port: 8080
        resources:
            cpu: 512
            memory: 1024
    metaflow-aws:ui: 
        image: docker.io/netflixoss/metaflow_metadata_service:v2.5.1
        port: 8083
        resources:
            cpu: 1024
            memory: 2048 # oom'ing on 1024, leading to missing stdout/stderr
    metaflow-aws:metadata-store:
        instance-class: db.t3.micro
        username: metaflow
        name: metaflow
        port: 5432
    metaflow-aws:batch:
        queues:
            - name: fargate-queue
              compute-environments:

                - name: fargate-ce
                  max_vcpus: 16
                  type: FARGATE

            - name: ec2-queue
              compute-environments:
              
                - name: ec2-cpu-ce
                  max_vcpus: 16
                  type: EC2
                  instance_types: [
                        "c7i.2xlarge",
                        "c7i.4xlarge",
                        "c7i.8xlarge",
                        "c7i.16xlarge",
                        "c7i.24xlarge",
                        "c8i.2xlarge",
                        "c8i.4xlarge",
                        "c8i.8xlarge",
                        "c8i.16xlarge",
                        "r7i.2xlarge",
                        "r7i.4xlarge",
                        "r7i.8xlarge",
                        "r7i.16xlarge",
                    ]

                - name: ec2-gpu-ce
                  max_vcpus: 16
                  type: EC2
                  instance_types: [
                        # General-purpose inference / smaller GPUs
                        "g4ad.xlarge", "g4ad.2xlarge", "g4ad.4xlarge",
                        "g4ad.8xlarge", "g4ad.16xlarge",

                        "g4dn.xlarge", "g4dn.2xlarge", "g4dn.4xlarge",
                        "g4dn.8xlarge", "g4dn.12xlarge", "g4dn.16xlarge",
                        "g4dn.metal",

                        "g5.xlarge", "g5.2xlarge", "g5.4xlarge",
                        "g5.8xlarge", "g5.12xlarge", "g5.16xlarge",
                        # "g5.24xlarge", "g5.48xlarge",

                        "g6.xlarge", "g6.2xlarge", "g6.4xlarge",
                        "g6.8xlarge", "g6.12xlarge", "g6.16xlarge",
                        # "g6.24xlarge", "g6.48xlarge",

                        # Newer GPU family
                        # # A100
                        # "p4d.24xlarge",

                    ]